"""Initial migration: create employees table

Revision ID: fa749791dfc6
Revises: 
Create Date: 2025-07-10 14:57:11.150988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa749791dfc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('idx_department'), table_name='employees')
    op.drop_index(op.f('idx_first_name'), table_name='employees')
    op.drop_index(op.f('idx_last_name'), table_name='employees')
    op.drop_index(op.f('idx_location'), table_name='employees')
    op.drop_index(op.f('idx_position'), table_name='employees')
    op.drop_index(op.f('idx_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.create_index('idx_dept_position', 'employees', ['department', 'position'], unique=False)
    op.create_index('idx_location_status', 'employees', ['location', 'status'], unique=False)
    op.create_index('idx_name_full', 'employees', ['first_name', 'last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_name_full', table_name='employees')
    op.drop_index('idx_location_status', table_name='employees')
    op.drop_index('idx_dept_position', table_name='employees')
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('idx_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('idx_position'), 'employees', ['position'], unique=False)
    op.create_index(op.f('idx_location'), 'employees', ['location'], unique=False)
    op.create_index(op.f('idx_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('idx_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('idx_department'), 'employees', ['department'], unique=False)
    op.alter_column('employees', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
